version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: medusa_user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: medusa-db
    ports:
      - "5436:5436"
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
